### ISSUE TITLE
Typo: secundary 

### ISSUE THREAD

**Issue by aoturoa** [JeroenHulscher/koop#124]
https://github.com/JeroenHulscher/koop/blob/e81198cf38e8109a8a32bf0192da505a6abcdc9f/src/%40koop-components/templates/attenderingsservice-templates/beh-dashboard.config.yml#L47

**Comment by aoturoa** [comment]
https://github.com/JeroenHulscher/koop/pull/125

**Comment by ruurdv** [comment]
Solved.
